# -*- coding: utf-8 -*-
"""File-backed skill helpers."""

from __future__ import annotations

from pathlib import Path

from fastapi import HTTPException, status

from src.server.config import global_config

from ..models import AgentSkill, AgentSkillCategory, AgentSkillTag


def ensure_skill_market_root() -> None:
    skill_market_root().mkdir(parents=True, exist_ok=True)


def read_skill_markdown(skill: AgentSkill) -> str:
    path = Path(skill.skill_path)
    if not path.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Skill 文件不存在")
    return path.read_text(encoding="utf-8")


def skill_market_root() -> Path:
    return Path(global_config.project_root) / "data" / "skill_market"


def skill_directory(skill_id: str) -> Path:
    return skill_market_root() / skill_id


def write_skill_files(directory: Path, skill_markdown: str, metadata: dict[str, object]) -> dict[str, Path]:
    directory.mkdir(parents=True, exist_ok=True)
    agents_dir = directory / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    skill_path = directory / "SKILL.md"
    metadata_path = agents_dir / "openai.yaml"
    skill_path.write_text(f"{skill_markdown.rstrip()}\n", encoding="utf-8")
    metadata_path.write_text(dump_generated_yaml(metadata), encoding="utf-8")
    return {"directory": directory, "skill_path": skill_path, "metadata_path": metadata_path}


def build_metadata(
    *,
    skill_id: str,
    name: str,
    description: str,
    category: AgentSkillCategory,
    tags: list[AgentSkillTag],
    visibility: str,
    created_at: str,
    updated_at: str,
) -> dict[str, object]:
    return {
        "id": skill_id,
        "name": name,
        "description": description,
        "mention": f"@{skill_id}",
        "category": category.id,
        "category_id": category.id,
        "category_label": category.name,
        "visibility": visibility,
        "tag_ids": [tag.id for tag in tags],
        "tags": [tag.name for tag in tags],
        "created_at": created_at,
        "updated_at": updated_at,
        "source": "admin",
        "managed_by": "pettech_show",
    }


def dump_generated_yaml(metadata: dict[str, object]) -> str:
    lines = ["# This file is generated by pettech_show. Edit through the admin UI."]
    for key, value in metadata.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {quote_yaml_scalar(str(item))}")
            continue
        lines.append(f"{key}: {quote_yaml_scalar(str(value))}")
    return "\n".join(lines) + "\n"


def quote_yaml_scalar(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
