# -*- coding: utf-8 -*-
"""Personal AI Wiki service public API."""

from __future__ import annotations

from .api import (
    create_job,
    delete_job,
    get_entry_page,
    get_file,
    get_job,
    get_result,
    get_workspace,
    list_jobs,
    update_job,
)
from .access import can_access_job, get_accessible_job, is_admin
from .persistence import (
    manifest_db_payload,
    read_answer,
    read_manifest,
    update_manifest,
    upsert_job_from_manifest,
    write_manifest,
)
from .queue import get_queue, reset_queue_for_tests
from .runner import (
    build_prompt,
    build_session_factory,
    prepare_skill,
    run_job,
    run_personal_aiwiki_opencode,
    sync_job_records,
    workspace_lock,
)
from .serializers import (
    build_result_from_job,
    build_stats,
    coerce_job_status,
    coerce_operation,
    job_out_from_model,
    job_summary_from_model,
    normalize_optional_text,
    parse_json_dict,
    parse_json_list,
    parse_uploaded_files,
)
from .uploads import (
    build_manifest,
    default_job_title,
    validate_uploads,
    write_one_upload,
    write_text_source,
    write_uploads,
)
from .workspace import (
    DEFAULT_SCHEMA,
    ensure_workspace,
    new_job_id,
    normalize_wiki_page,
    personal_aiwiki_root,
    resolve_wiki_page_path,
    user_job_dir,
    user_root,
    user_workspace_root,
)

__all__ = [
    "DEFAULT_SCHEMA",
    "build_manifest",
    "build_prompt",
    "build_result_from_job",
    "build_session_factory",
    "build_stats",
    "can_access_job",
    "coerce_job_status",
    "coerce_operation",
    "create_job",
    "default_job_title",
    "delete_job",
    "ensure_workspace",
    "get_entry_page",
    "get_accessible_job",
    "get_file",
    "get_job",
    "get_queue",
    "get_result",
    "get_workspace",
    "is_admin",
    "job_out_from_model",
    "job_summary_from_model",
    "list_jobs",
    "manifest_db_payload",
    "new_job_id",
    "normalize_optional_text",
    "normalize_wiki_page",
    "parse_json_dict",
    "parse_json_list",
    "parse_uploaded_files",
    "personal_aiwiki_root",
    "prepare_skill",
    "read_answer",
    "read_manifest",
    "reset_queue_for_tests",
    "resolve_wiki_page_path",
    "run_job",
    "run_personal_aiwiki_opencode",
    "sync_job_records",
    "update_job",
    "update_manifest",
    "upsert_job_from_manifest",
    "user_job_dir",
    "user_root",
    "user_workspace_root",
    "validate_uploads",
    "workspace_lock",
    "write_manifest",
    "write_one_upload",
    "write_text_source",
    "write_uploads",
]
